### ISSUE TITLE
Move to bioconda

### ISSUE THREAD

**Issue by nick-youngblut** [conda-forge/r-picante-feedstock#1]
@conda-forge/core: This R package is really only meant for bioinformatics. I should have added it to bioconda instead of conda-forge. Also, the feedstock is currently failing all tests. Is it alright to remove this feedstock and then add the recipe to bioconda?

**Comment by bgruening** [comment]
@nick-youngblut I'm would be ok with keeping it here, since it is already here. You are the maintainer so you can decide, but we don't have a procedure to remove a package for such a reason.

**Comment by nick-youngblut** [comment]
@bgruening it's just a bit confusing that most R packages on phylogeny are on bioconda, while this one is on conda-forge. This is my fault for adding it to conda-forge. Since you don't have a formal mechanism for removing a package, I'm ok with just keeping the package on conda-forge. That means that I need to get this feedstock passing, and I'm having problems trying to re-render the feedstock (I'm hoping that fixes the current failed tests).

**Comment by bgruening** [comment]
@conda-forge-admin, please rerender

**Comment by nick-youngblut** [comment]
Yeah, I forgot about conda-forge-admin. Thanks!

**Comment by bgruening** [comment]
Cool seems to be fixed.
